[workspace]
resolver = "2"

members = ["core"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
primitive-types = { version = "0.13.1", default-features = false }
log = "0.4.22"
env_logger = "0.11.5"